"use strict";
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ENUMS
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

exports.MemberPermissions = [
    "Admin",
    "Note",
    "Project.Add",
    "Project.View",
    "Project.Change",
    "Project.Delete",
    "Tasktype.Add",
    "Tasktype.View",
    "Tasktype.Change",
    "Tasktype.Delete",
    "Taskstatus.Add",
    "Taskstatus.View",
    "Taskstatus.Change",
    "Taskstatus.Delete",
    "Contact.Add",
    "Contact.View",
    "Contact.Change",
    "Contact.Change.Login",
    "Contact.Delete",
    "Member.Add",
    "Member.Add.Permission",
    "Member.View",
    "Member.Change",
    "Member.Change.Login",
    "Member.Change.Permission",
    "Member.Delete",
    "Task.Add",
    "Task.View",
    "Task.Change",
    "Task.Change.Project",
    "Task.Change.Type",
    "Task.Change.Contact",
    "Task.Change.Finish",
    "Task.Change.Prio",
    "Task.Change.Content",
    "Task.Delete",
    "Group.View",
    "Group.Change"
];
